### PR TITLE
Add option to disable certain autocommands

### PR DESCRIPTION
**Pull request by iamFIREcracker**
Sometimes I work on projects where Maven is only used to package things up and not to compile source files, and this plugin's default autocommands can really mess things up (especially when they start changing buffers `compiler` options).  This PR adds an option to disable some of these autocommands, and expose `SetupMavenEnv()`.

### CODE REVIEW

**Comment by mikelue** [comment]
How about we add something like:
```vim
let g:maven_plugin_ignore_file = [ "path1/*", "path2/*.java" ]
```

**Comment by iamFIREcracker** [comment]
Something like this? https://github.com/iamFIREcracker/vim-maven-plugin/commit/15ff2651115a94aeec728c899eb5fc44fdca9b61 I guess that could work too (I would then add the following in my .vimrc)

```
let g:maven_ignore_globs = [
            \ '\.js'
            \ ]
```

**Comment by mikelue** [comment]
Replaced by commit abf3ca4404b03c01bf91c4b55a0c336e24ce5ba9

**Comment by iamFIREcracker** [comment]
Awesome, thanks @mikelue !

**Pull request closed without merging**
